// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFBT4iVRxad6lg8Yyav3eKylSTwteLVfw',
    appId: '1:105137709861:web:2b50a55000c9ce5a2630cc',
    messagingSenderId: '105137709861',
    projectId: 'travel-b67db',
    authDomain: 'travel-b67db.firebaseapp.com',
    storageBucket: 'travel-b67db.appspot.com',
    measurementId: 'G-T4FY6X0LGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFpFq8v1SSvkzyD55HNKmKoo2XasqABG0',
    appId: '1:105137709861:android:ab74a60d3cf960fd2630cc',
    messagingSenderId: '105137709861',
    projectId: 'travel-b67db',
    storageBucket: 'travel-b67db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLoG5qym4UqQKqzoAbopUKNZVn2w6ba6U',
    appId: '1:105137709861:ios:31e910f0888b3f042630cc',
    messagingSenderId: '105137709861',
    projectId: 'travel-b67db',
    storageBucket: 'travel-b67db.appspot.com',
    iosBundleId: 'com.example.restoran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLoG5qym4UqQKqzoAbopUKNZVn2w6ba6U',
    appId: '1:105137709861:ios:31e910f0888b3f042630cc',
    messagingSenderId: '105137709861',
    projectId: 'travel-b67db',
    storageBucket: 'travel-b67db.appspot.com',
    iosBundleId: 'com.example.restoran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFBT4iVRxad6lg8Yyav3eKylSTwteLVfw',
    appId: '1:105137709861:web:dc6d819857fd68412630cc',
    messagingSenderId: '105137709861',
    projectId: 'travel-b67db',
    authDomain: 'travel-b67db.firebaseapp.com',
    storageBucket: 'travel-b67db.appspot.com',
    measurementId: 'G-3M12K47297',
  );
}
